-- -- role_taikhoan
-- insert into `role_taikhoan` (id, title)
-- values (0, 'ADMIN'),
--        (1, 'EMPLOYEE');
-- -- taikhoan
-- INSERT INTO taikhoan (username, password, status)
-- VALUES ('ThuNTM', '001225145523', 1),
--        ('TaiNG', '001478111451', 1);
-- -- nhóm máu
-- INSERT INTO nhom_mau (id, name)
-- values (0, 'A'),
--        (1, 'B'),
--        (2, 'AB'),
--        (3, 'O');
-- -- tinh_trang_suc_khoe
-- INSERT into tinh_trang_suc_khoe (title)
-- VALUES ('YẾU'),
--        ('TRUNG BÌNH'),
--        ('KHÁ'),
--        ('TỐT'),
--        ('KHỎE');
-- -- doi_tuong_chinh_sach
-- INSERT INTO doi_tuong_chinh_sach (name)
-- values ('Dân tộc thiểu số'),
--        ('Con liệt sĩ');
-- -- trinh_do_giao_duc_pho_thong
-- INSERT INTO trinh_do_giao_duc_pho_thong (name)
-- values ('10/10'),
--        ('12/12');
-- -- trinh_do_chuyen_mon
-- INSERT INTO trinh_do_chuyen_mon (name)
-- values ('Sơ cấp'),
--        ('Trung cấp'),
--        ('Cao đẳng'),
--        ('Đại học'),
--        ('Thạc sĩ'),
--        ('Tiến sĩ');
-- -- học hàm
-- INSERT INTO hoc_ham (name)
-- values ('Giáo sư'),
--        ('Phó giáo sư');
-- -- danh_hieu_nha_nuoc_phong_tang
-- INSERT INTO danh_hieu_nha_nuoc_phong_tang (name)
-- values ('Tỉnh Anh hùng'),
--        ('Thành phố Anh hùng'),
--        ('Bà mẹ Việt Nam Anh hùng'),
--        ('Anh hùng Lực lượng vũ trang nhân dân'),
--        ('Anh hùng Lao động'),
--        ('Nhà giáo nhân dân'),
--        ('Nhà giáo ưu tú');
-- -- dân tộc
-- INSERT INTO dan_toc (id, name)
-- VALUES (1, "Ba Na"),
--        (2, "Bà Y"),
--        (3, "Bố Y"),
--        (4, "Brau"),
--        (5, "Bru - Vân Kiều"),
--        (6, "Chăm"),
--        (7, "Chơ Ro"),
--        (8, "Chứt"),
--        (9, "Cơ Ho"),
--        (10, "Cơ Tu"),
--        (11, "Cống"),
--        (12, "Coong"),
--        (13, "Cờ Lao"),
--        (14, "Ê Đê"),
--        (15, "Gia Rai"),
--        (16, "Giáy"),
--        (17, "Hà Nhì"),
--        (18, "Hrê"),
--        (19, "Kháng"),
--        (20, "Khơ Mú"),
--        (21, "Khơ Lơ"),
--        (22, "Kinh"),
--        (23, "Krông"),
--        (24, "Lào"),
--        (25, "La Chí"),
--        (26, "La Ha"),
--        (27, "Lô Lô"),
--        (28, "Mảng"),
--        (29, "M'nông"),
--        (30, "Mơ Nông"),
--        (31, "Mường"),
--        (32, "Nùng"),
--        (33, "Ô Đu"),
--        (34, "Pà Thẻn"),
--        (35, "Phù Lá"),
--        (36, "Pu Péo"),
--        (37, "Rơ Măm"),
--        (38, "Ra Glai"),
--        (39, "Rục"),
--        (40, "Sán Chay"),
--        (41, "Sán Dìu"),
--        (42, "Sán Rìu"),
--        (43, "Si La"),
--        (44, "Sơ Rếch"),
--        (45, "Tày"),
--        (46, "Tày Thái"),
--        (47, "Thổ"),
--        (48, "Thái"),
--        (49, "Xinh Mun"),
--        (50, "Xơ Đăng"),
--        (51, "X' Tiêng"),
--        (52, "Ya Chêng"),
--        (53, "Ý Đình"),
--        (54, "Zao");
-- -- giới tính
-- insert into gioi_tinh (id, name)
-- VALUES (0, 'Nam'),
--        (1, 'Nữ');
-- -- tôn giáo
-- insert into ton_giao (id, name)
-- VALUES (0, 'Phật giáo'),
--        (1, 'Công giáo'),
--        (3, 'Tin Lành');
-- -- thành phần gia đình
-- insert into thanh_phan_gia_dinh (id, name)
-- VALUES (0, 'Cố nông'),
--        (1, 'Bần nông'),
--        (3, 'Trung nông'),
--        (4, 'Phú nông/ Địa chủ'),
--        (5, 'Công chức/ Viên chức'),
--        (6, 'Nghèo đói'),
--        (7, 'Tiểu thương'),
--        (8, 'Tiểu chủ'),
--        (9, 'Tư sản'),
--        (10, 'Tiểu tư sản');